import type { Metadata } from 'next'
import { Lato } from 'next/font/google'
import './globals.css'
import { ClerkProvider } from '@clerk/nextjs'
import { plPL } from '@clerk/localizations'

const lato = Lato({ weight: '400', subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'PARAGONE',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider localization={plPL}>
      <html lang="en">
        <body
          className={`${lato.className} mx-auto min-h-screen w-[393px] bg-[#D9D9D9] text-[#383838]`}
        >
          <main className="">
            <div className="">{children}</div>
          </main>
        </body>
      </html>
    </ClerkProvider>
  )
}
