import type { Metadata } from 'next'
import { Lato } from 'next/font/google'
import './globals.css'
import { ClerkProvider } from '@clerk/nextjs'

const lato = Lato({ weight: '400', subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'PARAGONE',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${lato.className} max-w-[393px] bg-[#D9D9D9]`}>
          <main className="">
            <div className="">{children}</div>
          </main>
        </body>
      </html>
    </ClerkProvider>
  )
}
